name: Dolt Action

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch: # Run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dolt
        run: |
          sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'

      - name: Clone juicebox repository
        run: dolt clone jigglyjams/juicebox $HOME/juicebox

      - name: Change dir, run dolt dump and save output
        run: cd $HOME/juicebox && dolt dump
                
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Upload output to IPFS
        id: ipfsPin
        env:
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INFURA_IPFS_ID: ${{ secrets.INFURA_IPFS_ID }}
          INFURA_IPFS_SECRET: ${{ secrets.INFURA_IPFS_SECRET }}
          IPFS_GATEWAY: ${{ secrets.IPFS_GATEWAY }}
        run: |
          npm install axios form-data dotenv
          node ipfsPin.js $HOME/juicebox/doltdump.sql
